### PR TITLE
 bump the docker image versions for the Terra notebooks

### PR DESCRIPTION
**Pull request by amygdala**
... plus typo fix

### CODE REVIEW

**Review by deflaux — APPROVED** [review]
Looks good and thank you for the typo fix!

Can you please also update the Docker tag in the rest of the notebooks that use image `ghcr.io/broadinstitute/ml4h/ml4h_terra`?

**Comment by deflaux** [comment]
This change also fixes https://github.com/broadinstitute/ml4h/issues/456

**Comment by amygdala** [comment]
Sorry, I spaced that the `review_results` ones needed updating.  PTAL. (did I miss anything else?) @deflaux

**Review by deflaux — APPROVED** [review]
lg, thanks @amygdala !

**Pull request merged**
