### PR TITLE
dockerfile requirements file munging

### PR DESCRIPTION
**Pull request by amygdala**
With the Terra image build, need to remove TF from the requirements list (it's now installed in the base image), and unpin some related installs.

### CODE REVIEW

**Comment by amygdala** [comment]
Marked as 'draft' until I've tested all the notebooks.

**Comment by amygdala** [comment]
The test build is failing b/c it can't find the downloaded `tensorflow-requirements.txt` file.  It all works fine with my local docker build— it may be that the file path needs to be more explicitly specified for the remote build for some reason.  (Will investigate tomorrow).

**Comment by amygdala** [comment]
I think we're set.... if it looks good to you, let's pull it in to master and then generate the official build. @deflaux 
I'll do another test with that before updating the nbs with the new info.

**Review by deflaux — APPROVED** [review]
Looks good @amygdala 

Thanks for pinning ipyannotations to 0.2.1 for now. I still need to incorporate the recent changes to that package.

**Pull request merged**
