### PR TITLE
Configure continuous integration of ml4h Python package via GitHub Actions.

### PR DESCRIPTION
**Pull request by deflaux**
For every pull request, ensure that the Python package builds and is able to run the "not slow" tests.

Note that some of the tests currently fail. I saw the same failures when running `pytest tests -m "not slow"` within image `gcr.io/broad-ml4cvd/deeplearning:tf2-latest-cpu`.

Other changes include:
* `setup.py` now installs package dependencies
* removed an obsolete reference to `TMAPS` from the tests
* added tensorflow dependency to `docker/vm_boot_images/config/tensorflow-requirements.txt` which is needed for a general install of the Python package and redundant in the context of `ml4h/docker/vm_boot_images/Dockerfile`
* updated contributing documentation to 'ml4h'

### CODE REVIEW

**Comment by deflaux** [comment]
Take a look at the most recent run of the workflow here: https://github.com/deflaux/ml4h/actions

**Review by lucidtronix — CHANGES_REQUESTED** [review]
Awesome thank you Nicole! Before merging with master can you merge the branch `sf_fix_tests` into this one and check if the not slow tests all start passing?

**Comment by deflaux** [comment]
It passes now! https://github.com/deflaux/ml4h/actions/runs/354496806

**Review by lucidtronix — APPROVED** [review]
Merge Away!

**Pull request merged**
